name: Build Documentation

on:
  push:
    branches:
      - main
  release:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: build
          auto-update-conda: true

      - name: install requirements
        run: >-
          conda install -n build -c conda-forge
          --file requirements/build.txt
          --file requirements/run.txt
          --file requirements/docs.txt
          --quiet --yes

      - name: install the package
        run: python -m pip install . --no-deps

      - name: build documents
        run: make -C doc html

      - name: Run tests and upload coverage
        shell: bash -l {0}
        run: |
          conda activate test
          coverage run -m pytest -vv -s
          coverage report -m
          codecov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/build/html
